### ISSUE TITLE
Do not edit the Makefile in travis build

### ISSUE THREAD

**Issue by darnir** [neomutt/travis-build#2]
In general editing any autogenerated script is a bad idea. And when doing CI, it's a particularly bad idea to modify the Makefile itself.

In the future, this may make some debugging extremely hard as we may not realise where the issue is, the modified makefile or the code itself. The cost of building the docs and a few other things isn't that great. I would vote for using the pristine makefile

**Comment by flatcap** [comment]
> **In general** editing any autogenerated script is a bad idea

In general (my emphasis), I agree.  In this case I've got a few things on my mind.

**Travis is a free service**.  If I can save a few CPU cycles, I'd like to.

**Debugging**.  I don't think this is a problem.  If I were testing the build on lots of strange architectures, or compilers, then I'd want as much information as possible.  All I'm doing on Travis, is building every combination of configuration.  If a build fails, I just need the commit hash and the config string -- I'll build and debug the problem on my own machine.

**Makefile**  The Mutt build is a **mess**.  The compiler generates lots of warnings.  Most of them aren't a problem, but they make it hard to spot new warnings.  By carefully editing the Makefile, I've prevented a lot of visual clutter in the output.  If I need to look at the logs, it should be easier to find what I'm looking for.

**Note:** I still need to check that my build scripts work on OSX.  I've already introduced one OSX bug.

For now, I'm going to leave the build script as it is.
However, I give you a free pass to shout "Haha!  I told you so!" if I'm wrong :-)
